/// @file sharedData.h
// This header file was written by K.O. (2025 - 2026)

#ifndef SHARED_DATA_H
#define SHARED_DATA_H

#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>

#include "modbusConfig.h"

//..............................................................................
// Modbus Coil Address Mnemonics (from ModbusRegisters.csv)
//..............................................................................

#define MODBUS_ADDR_CUP1_CONTROL 1
#define MODBUS_ADDR_CUP1_SWITCH 3
#define MODBUS_ADDR_CUP2_CONTROL 5
#define MODBUS_ADDR_EXTERNAL_INHIBITION 6
#define MODBUS_ADDR_CUP2_SWITCH 7
#define MODBUS_ADDR_CUP3_CONTROL 9
#define MODBUS_ADDR_CUP3_SWITCH1 11
#define MODBUS_ADDR_CUP3_SWITCH2 12
#define MODBUS_ADDR_CUP1_REQUESTED_STATE 13
#define MODBUS_ADDR_CUP2_REQUESTED_STATE 14
#define MODBUS_ADDR_CUP3_REQUESTED_STATE 15
#define MODBUS_ADDR_CUP1_STEADY 16
#define MODBUS_ADDR_CUP2_STEADY 17
#define MODBUS_ADDR_CUP3_STEADY 18
#define MODBUS_ADDR_CUP1_INSERTED 19
#define MODBUS_ADDR_CUP2_INSERTED 20
#define MODBUS_ADDR_CUP3_INSERTED 21
#define MODBUS_ADDR_ACTUATOR1_CONTROL 22
#define MODBUS_ADDR_ACTUATOR2_CONTROL 23
#define MODBUS_ADDR_ACTUATOR3_CONTROL_IN 24
#define MODBUS_ADDR_ACTUATOR3_CONTROL_OUT 25
#define MODBUS_ADDR_ACTUATOR3_CONTROL_BRAKE 26

//..............................................................................
// Modbus Holding Register Address Mnemonics (from ModbusRegisters.csv)
//..............................................................................

#define MODBUS_ADDR_ERROR_CODE 1000
#define MODBUS_ADDR_LAST_ERROR 1001
#define MODBUS_ADDR_ERROR_STORAGE 1002
#define MODBUS_ADDR_TIME_LIMIT_INSERTING_1 1003
#define MODBUS_ADDR_TIME_LIMIT_INSERTING_2 1004
#define MODBUS_ADDR_TIME_LIMIT_INSERTING_3 1005
#define MODBUS_ADDR_TIME_LIMIT_WITHDRAWING_1 1006
#define MODBUS_ADDR_TIME_LIMIT_WITHDRAWING_2 1007
#define MODBUS_ADDR_TIME_LIMIT_WITHDRAWING_3 1008
#define MODBUS_ADDR_ACTIVE_CUP 1009
#define MODBUS_ADDR_CUP1_ERROR 1010
#define MODBUS_ADDR_CUP2_ERROR 1011
#define MODBUS_ADDR_CUP3_ERROR 1012
#define MODBUS_ADDR_CUP1_LAST_ERROR 1013
#define MODBUS_ADDR_CUP2_LAST_ERROR 1014
#define MODBUS_ADDR_CUP3_LAST_ERROR 1015
#define MODBUS_ADDR_CUP1_ERROR_STORAGE 1016
#define MODBUS_ADDR_CUP2_ERROR_STORAGE 1017
#define MODBUS_ADDR_CUP3_ERROR_STORAGE 1018
#define MODBUS_ADDR_INSTALLED_CUPS 1019
#define MODBUS_ADDR_ELECTRODES_CUP1 1020
#define MODBUS_ADDR_ELECTRODES_CUP2 1021
#define MODBUS_ADDR_ELECTRODES_CUP3 1022
#define MODBUS_ADDR_CUP1_TYPE 1023
#define MODBUS_ADDR_CUP2_TYPE 1024
#define MODBUS_ADDR_CUP3_TYPE 1025
#define MODBUS_ADDR_CUP1_CH1_GAIN1_OFFSET 1026
#define MODBUS_ADDR_CUP1_CH2_GAIN1_OFFSET 1027
#define MODBUS_ADDR_CUP1_CH3_GAIN1_OFFSET 1028
#define MODBUS_ADDR_CUP1_CH4_GAIN1_OFFSET 1029
#define MODBUS_ADDR_CUP2_CH1_GAIN1_OFFSET 1030
#define MODBUS_ADDR_CUP2_CH2_GAIN1_OFFSET 1031
#define MODBUS_ADDR_CUP2_CH3_GAIN1_OFFSET 1032
#define MODBUS_ADDR_CUP2_CH4_GAIN1_OFFSET 1033
#define MODBUS_ADDR_CUP3_CH1_GAIN1_OFFSET 1034
#define MODBUS_ADDR_CUP3_CH2_GAIN1_OFFSET 1035
#define MODBUS_ADDR_CUP3_CH3_GAIN1_OFFSET 1036
#define MODBUS_ADDR_CUP3_CH4_GAIN1_OFFSET 1037
#define MODBUS_ADDR_CUP1_CH1_GAIN2_OFFSET 1038
#define MODBUS_ADDR_CUP1_CH2_GAIN2_OFFSET 1039
#define MODBUS_ADDR_CUP1_CH3_GAIN2_OFFSET 1040
#define MODBUS_ADDR_CUP1_CH4_GAIN2_OFFSET 1041
#define MODBUS_ADDR_CUP2_CH1_GAIN2_OFFSET 1042
#define MODBUS_ADDR_CUP2_CH2_GAIN2_OFFSET 1043
#define MODBUS_ADDR_CUP2_CH3_GAIN2_OFFSET 1044
#define MODBUS_ADDR_CUP2_CH4_GAIN2_OFFSET 1045
#define MODBUS_ADDR_CUP3_CH1_GAIN2_OFFSET 1046
#define MODBUS_ADDR_CUP3_CH2_GAIN2_OFFSET 1047
#define MODBUS_ADDR_CUP3_CH3_GAIN2_OFFSET 1048
#define MODBUS_ADDR_CUP3_CH4_GAIN2_OFFSET 1049
#define MODBUS_ADDR_CUP1_CH1_GAIN1_FACTOR 1050
#define MODBUS_ADDR_CUP1_CH2_GAIN1_FACTOR 1051
#define MODBUS_ADDR_CUP1_CH3_GAIN1_FACTOR 1052
#define MODBUS_ADDR_CUP1_CH4_GAIN1_FACTOR 1053
#define MODBUS_ADDR_CUP2_CH1_GAIN1_FACTOR 1054
#define MODBUS_ADDR_CUP2_CH2_GAIN1_FACTOR 1055
#define MODBUS_ADDR_CUP2_CH3_GAIN1_FACTOR 1056
#define MODBUS_ADDR_CUP2_CH4_GAIN1_FACTOR 1057
#define MODBUS_ADDR_CUP3_CH1_GAIN1_FACTOR 1058
#define MODBUS_ADDR_CUP3_CH2_GAIN1_FACTOR 1059
#define MODBUS_ADDR_CUP3_CH3_GAIN1_FACTOR 1060
#define MODBUS_ADDR_CUP3_CH4_GAIN1_FACTOR 1061
#define MODBUS_ADDR_CUP1_CH1_GAIN2_FACTOR 1062
#define MODBUS_ADDR_CUP1_CH2_GAIN2_FACTOR 1063
#define MODBUS_ADDR_CUP1_CH3_GAIN2_FACTOR 1064
#define MODBUS_ADDR_CUP1_CH4_GAIN2_FACTOR 1065
#define MODBUS_ADDR_CUP2_CH1_GAIN2_FACTOR 1066
#define MODBUS_ADDR_CUP2_CH2_GAIN2_FACTOR 1067
#define MODBUS_ADDR_CUP2_CH3_GAIN2_FACTOR 1068
#define MODBUS_ADDR_CUP2_CH4_GAIN2_FACTOR 1069
#define MODBUS_ADDR_CUP3_CH1_GAIN2_FACTOR 1070
#define MODBUS_ADDR_CUP3_CH2_GAIN2_FACTOR 1071
#define MODBUS_ADDR_CUP3_CH3_GAIN2_FACTOR 1072
#define MODBUS_ADDR_CUP3_CH4_GAIN2_FACTOR 1073
#define MODBUS_ADDR_RANGE_CHANGE_THRESHOLD 1074
#define MODBUS_ADDR_CUP1_CH1_LOWER_LIMIT 1075
#define MODBUS_ADDR_CUP1_CH2_LOWER_LIMIT 1076
#define MODBUS_ADDR_CUP1_CH3_LOWER_LIMIT 1077
#define MODBUS_ADDR_CUP1_CH4_LOWER_LIMIT 1078
#define MODBUS_ADDR_CUP2_CH1_LOWER_LIMIT 1079
#define MODBUS_ADDR_CUP2_CH2_LOWER_LIMIT 1080
#define MODBUS_ADDR_CUP2_CH3_LOWER_LIMIT 1081
#define MODBUS_ADDR_CUP2_CH4_LOWER_LIMIT 1082
#define MODBUS_ADDR_CUP3_CH1_LOWER_LIMIT 1083
#define MODBUS_ADDR_CUP3_CH2_LOWER_LIMIT 1084
#define MODBUS_ADDR_CUP3_CH3_LOWER_LIMIT 1085
#define MODBUS_ADDR_CUP3_CH4_LOWER_LIMIT 1086
#define MODBUS_ADDR_CUP1_CH1_UPPER_LIMIT 1087
#define MODBUS_ADDR_CUP1_CH2_UPPER_LIMIT 1088
#define MODBUS_ADDR_CUP1_CH3_UPPER_LIMIT 1089
#define MODBUS_ADDR_CUP1_CH4_UPPER_LIMIT 1090
#define MODBUS_ADDR_CUP2_CH1_UPPER_LIMIT 1091
#define MODBUS_ADDR_CUP2_CH2_UPPER_LIMIT 1092
#define MODBUS_ADDR_CUP2_CH3_UPPER_LIMIT 1093
#define MODBUS_ADDR_CUP2_CH4_UPPER_LIMIT 1094
#define MODBUS_ADDR_CUP3_CH1_UPPER_LIMIT 1095
#define MODBUS_ADDR_CUP3_CH2_UPPER_LIMIT 1096
#define MODBUS_ADDR_CUP3_CH3_UPPER_LIMIT 1097
#define MODBUS_ADDR_CUP3_CH4_UPPER_LIMIT 1098
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_IN 1099
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_IN_RAND 1100
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_OUT 1101
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_OUT_RAND 1102
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_IN 1103
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_IN_RAND 1104
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_OUT 1105
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_OUT_RAND 1106
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_IN 1107
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_IN_RAND 1108
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_OUT 1109
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_OUT_RAND 1110
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE1 1111
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE2 1112
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE3 1113
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE4 1114
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE1 1115
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE2 1116
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE3 1117
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE4 1118
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE1 1119
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE2 1120
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE3 1121
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE4 1122
#define MODBUS_ADDR_SIM_AMPLIFIER_RANDOM_RATE 1123
#define MODBUS_ADDR_SIM_AMPLIFIER_RANDOM_OFFSET 1124
#define MODBUS_ADDR_SIM_EXTERNAL_LOCK_PERIOD 1125
#define MODBUS_ADDR_SIM_EXTERNAL_LOCK_DURATION 1126
#define MODBUS_ADDR_SIM_EXTERNAL_LOCK_DELAY 1127
#define MODBUS_ADDR_SIM_EVENT_CODE 1128
#define MODBUS_ADDR_SIM_EVENT_PERIOD 1129
#define MODBUS_ADDR_SIM_EVENT_DURATION 1130
#define MODBUS_ADDR_SIM_EVENT_DELAY 1131

//..............................................................................
// Modbus Input Register Address Mnemonics (from ModbusRegisters.csv)
//..............................................................................

#define MODBUS_ADDR_CUP1_CH1_SAMPLE 3001
#define MODBUS_ADDR_CUP1_CH2_SAMPLE 3002
#define MODBUS_ADDR_CUP1_CH3_SAMPLE 3003
#define MODBUS_ADDR_CUP1_CH4_SAMPLE 3004
#define MODBUS_ADDR_CUP1_CHANNEL_ERROR 3005
#define MODBUS_ADDR_CUP2_CH1_SAMPLE 3006
#define MODBUS_ADDR_CUP2_CH2_SAMPLE 3007
#define MODBUS_ADDR_CUP2_CH3_SAMPLE 3008
#define MODBUS_ADDR_CUP2_CH4_SAMPLE 3009
#define MODBUS_ADDR_CUP2_CHANNEL_ERROR 3010
#define MODBUS_ADDR_CUP3_CH1_SAMPLE 3011
#define MODBUS_ADDR_CUP3_CH2_SAMPLE 3012
#define MODBUS_ADDR_CUP3_CH3_SAMPLE 3013
#define MODBUS_ADDR_CUP3_CH4_SAMPLE 3014
#define MODBUS_ADDR_CUP3_CHANNEL_ERROR 3015

#define MODBUS_COILS_ADDRESS                MODBUS_ADDR_CUP1_CONTROL

/// This is the number of coils (as defined by Modbus); some of them are read-only, while others are read-write
#define MODBUS_COILS_NUMBER                 (MODBUS_ADDR_ACTUATOR3_CONTROL_BRAKE - MODBUS_ADDR_CUP1_CONTROL + 1)

// This directive specifies the starting address of the register area
#define MODBUS_HOLDING_REGISTERS_ADDRESS    MODBUS_ADDR_ERROR_CODE

// The initial registers are of type r/w; this directive specifies number of the r/w registers
#define MODBUS_HOLDING_REGISTERS_NUMBER     (MODBUS_ADDR_SIM_EVENT_DELAY - MODBUS_ADDR_ERROR_CODE + 1)

#define MODBUS_INPUT_REGISTERS_ADDRESS      MODBUS_ADDR_CUP1_CH1_SAMPLE

/// This is the number of read-only input registers
#define MODBUS_INPUT_REGISTERS_NUMBER       (MODBUS_ADDR_CUP3_CHANNEL_ERROR - MODBUS_ADDR_CUP1_CH1_SAMPLE + 1)

#define DEFAULT_ANALOG_RANGE_CHANGE_THRESHOLD 175u  // experimentally determined value

//..............................................................................
// Definitions of variables concerning Modbus communication
//..............................................................................

extern uint16_t ModbusInputRegisters[MODBUS_INPUT_REGISTERS_NUMBER];
extern bool ModbusCoils[MODBUS_COILS_NUMBER];
extern bool CoilsChanged[MODBUS_COILS_NUMBER];
extern uint16_t ModbusHoldingRegisters[MODBUS_HOLDING_REGISTERS_NUMBER];


uint16_t holdingIndexFromAddress(uint16_t address);

uint16_t inputIndexFromAddress(uint16_t address);

uint16_t coilIndexFromAddress(uint16_t address);




#endif // SHARED_DATA_H