/// @file sharedData.h
// This header file was written by K.O. (2025 - 2026)

#ifndef SHARED_DATA_H
#define SHARED_DATA_H

#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>

#include "modbusConfig.h"

//..............................................................................
// Modbus Coil Address Mnemonics (from ModbusRegisters.csv)
//..............................................................................

#define MODBUS_ADDR_CUP1_CONTROL 1
#define MODBUS_ADDR_EXTERNAL_INHIBITION1 2
#define MODBUS_ADDR_CUP1_SWITCH 3
			
#define MODBUS_ADDR_CUP2_CONTROL 5
#define MODBUS_ADDR_EXTERNAL_INHIBITION2 6
#define MODBUS_ADDR_CUP2_SWITCH 7
			
#define MODBUS_ADDR_CUP3_CONTROL 9
#define MODBUS_ADDR_EXTERNAL_INHIBITION3 10
#define MODBUS_ADDR_CUP3_SWITCH_A 11
#define MODBUS_ADDR_CUP3_SWITCH_B 12
#define MODBUS_ADDR_CUP1_ERROR_RECOVERY 13
#define MODBUS_ADDR_CUP2_ERROR_RECOVERY 14
#define MODBUS_ADDR_CUP3_ERROR_RECOVERY 15
#define MODBUS_ADDR_CUP1_REQUESTED_STATE 16
#define MODBUS_ADDR_CUP2_REQUESTED_STATE 17
#define MODBUS_ADDR_CUP3_REQUESTED_STATE 18
#define MODBUS_ADDR_ACTUATOR1_CONTROL 19
#define MODBUS_ADDR_ACTUATOR2_CONTROL 20
#define MODBUS_ADDR_ACTUATOR3_CONTROL_IN 21
#define MODBUS_ADDR_ACTUATOR3_CONTROL_OUT 22
#define MODBUS_ADDR_ACTUATOR3_CONTROL_BRAKE 23

#define MODBUS_ADDR_THE_LAST_COIL 23

//..............................................................................
// Modbus Holding Register Address Mnemonics (from ModbusRegisters.csv)
//..............................................................................

#define MODBUS_ADDR_ERROR_CODE 1000
#define MODBUS_ADDR_LAST_ERROR 1001
#define MODBUS_ADDR_ERROR_STORAGE 1002
#define MODBUS_ADDR_TIME_LIMIT_INSERTING1 1003
#define MODBUS_ADDR_TIME_LIMIT_INSERTING2 1004
#define MODBUS_ADDR_TIME_LIMIT_INSERTING3 1005
#define MODBUS_ADDR_TIME_LIMIT_WITHDRAWING1 1006
#define MODBUS_ADDR_TIME_LIMIT_WITHDRAWING2 1007
#define MODBUS_ADDR_TIME_LIMIT_WITHDRAWING3 1008
#define MODBUS_ADDR_ACTIVE_CUP 1009
#define MODBUS_ADDR_CUP1_FSM_STATE 1010
#define MODBUS_ADDR_CUP2_FSM_STATE 1011
#define MODBUS_ADDR_CUP3_FSM_STATE 1012
#define MODBUS_ADDR_CUP1_ERROR 1013
#define MODBUS_ADDR_CUP2_ERROR 1014
#define MODBUS_ADDR_CUP3_ERROR 1015
#define MODBUS_ADDR_CUP1_LAST_ERROR 1016
#define MODBUS_ADDR_CUP2_LAST_ERROR 1017
#define MODBUS_ADDR_CUP3_LAST_ERROR 1018
#define MODBUS_ADDR_CUP1_ERROR_STORAGE 1019
#define MODBUS_ADDR_CUP2_ERROR_STORAGE 1020
#define MODBUS_ADDR_CUP3_ERROR_STORAGE 1021
#define MODBUS_ADDR_INSTALLED_CUPS 1022
#define MODBUS_ADDR_ELECTRODES_CUP1 1023
#define MODBUS_ADDR_ELECTRODES_CUP2 1024
#define MODBUS_ADDR_ELECTRODES_CUP3 1025
#define MODBUS_ADDR_CUP1_TYPE 1026
#define MODBUS_ADDR_CUP2_TYPE 1027
#define MODBUS_ADDR_CUP3_TYPE 1028
#define MODBUS_ADDR_CALIBRATION_CURRENT1 1029
#define MODBUS_ADDR_CALIBRATION_CURRENT2 1030
#define MODBUS_ADDR_CALIBRATION_CURRENT3 1031
#define MODBUS_ADDR_CALIBRATION_CURRENT4 1032
#define MODBUS_ADDR_CUP1_CHANNEL1_GAIN_LOW_POINT1 1033
#define MODBUS_ADDR_CUP1_CHANNEL1_GAIN_LOW_POINT2 1034
#define MODBUS_ADDR_CUP1_CHANNEL1_GAIN_LOW_POINT3 1035
#define MODBUS_ADDR_CUP1_CHANNEL1_GAIN_HIGH_POINT2 1036
#define MODBUS_ADDR_CUP1_CHANNEL1_GAIN_HIGH_POINT3 1037
#define MODBUS_ADDR_CUP1_CHANNEL1_GAIN_HIGH_POINT4 1038
#define MODBUS_ADDR_CUP1_CHANNEL2_GAIN_LOW_POINT1 1039
#define MODBUS_ADDR_CUP1_CHANNEL2_GAIN_LOW_POINT2 1040
#define MODBUS_ADDR_CUP1_CHANNEL2_GAIN_LOW_POINT3 1041
#define MODBUS_ADDR_CUP1_CHANNEL2_GAIN_HIGH_POINT2 1042
#define MODBUS_ADDR_CUP1_CHANNEL2_GAIN_HIGH_POINT3 1043
#define MODBUS_ADDR_CUP1_CHANNEL2_GAIN_HIGH_POINT4 1044
#define MODBUS_ADDR_CUP1_CHANNEL3_GAIN_LOW_POINT1 1045
#define MODBUS_ADDR_CUP1_CHANNEL3_GAIN_LOW_POINT2 1046
#define MODBUS_ADDR_CUP1_CHANNEL3_GAIN_LOW_POINT3 1047
#define MODBUS_ADDR_CUP1_CHANNEL3_GAIN_HIGH_POINT2 1048
#define MODBUS_ADDR_CUP1_CHANNEL3_GAIN_HIGH_POINT3 1049
#define MODBUS_ADDR_CUP1_CHANNEL3_GAIN_HIGH_POINT4 1050
#define MODBUS_ADDR_CUP1_CHANNEL4_GAIN_LOW_POINT1 1051
#define MODBUS_ADDR_CUP1_CHANNEL4_GAIN_LOW_POINT2 1052
#define MODBUS_ADDR_CUP1_CHANNEL4_GAIN_LOW_POINT3 1053
#define MODBUS_ADDR_CUP1_CHANNEL4_GAIN_HIGH_POINT2 1054
#define MODBUS_ADDR_CUP1_CHANNEL4_GAIN_HIGH_POINT3 1055
#define MODBUS_ADDR_CUP1_CHANNEL4_GAIN_HIGH_POINT4 1056
#define MODBUS_ADDR_CUP2_CHANNEL1_GAIN_LOW_POINT1 1057
#define MODBUS_ADDR_CUP2_CHANNEL1_GAIN_LOW_POINT2 1058
#define MODBUS_ADDR_CUP2_CHANNEL1_GAIN_LOW_POINT3 1059
#define MODBUS_ADDR_CUP2_CHANNEL1_GAIN_HIGH_POINT2 1060
#define MODBUS_ADDR_CUP2_CHANNEL1_GAIN_HIGH_POINT3 1061
#define MODBUS_ADDR_CUP2_CHANNEL1_GAIN_HIGH_POINT4 1062
#define MODBUS_ADDR_CUP2_CHANNEL2_GAIN_LOW_POINT1 1063
#define MODBUS_ADDR_CUP2_CHANNEL2_GAIN_LOW_POINT2 1064
#define MODBUS_ADDR_CUP2_CHANNEL2_GAIN_LOW_POINT3 1065
#define MODBUS_ADDR_CUP2_CHANNEL2_GAIN_HIGH_POINT2 1066
#define MODBUS_ADDR_CUP2_CHANNEL2_GAIN_HIGH_POINT3 1067
#define MODBUS_ADDR_CUP2_CHANNEL2_GAIN_HIGH_POINT4 1068
#define MODBUS_ADDR_CUP2_CHANNEL3_GAIN_LOW_POINT1 1069
#define MODBUS_ADDR_CUP2_CHANNEL3_GAIN_LOW_POINT2 1070
#define MODBUS_ADDR_CUP2_CHANNEL3_GAIN_LOW_POINT3 1071
#define MODBUS_ADDR_CUP2_CHANNEL3_GAIN_HIGH_POINT2 1072
#define MODBUS_ADDR_CUP2_CHANNEL3_GAIN_HIGH_POINT3 1073
#define MODBUS_ADDR_CUP2_CHANNEL3_GAIN_HIGH_POINT4 1074
#define MODBUS_ADDR_CUP2_CHANNEL4_GAIN_LOW_POINT1 1075
#define MODBUS_ADDR_CUP2_CHANNEL4_GAIN_LOW_POINT2 1076
#define MODBUS_ADDR_CUP2_CHANNEL4_GAIN_LOW_POINT3 1077
#define MODBUS_ADDR_CUP2_CHANNEL4_GAIN_HIGH_POINT2 1078
#define MODBUS_ADDR_CUP2_CHANNEL4_GAIN_HIGH_POINT3 1079
#define MODBUS_ADDR_CUP2_CHANNEL4_GAIN_HIGH_POINT4 1080
#define MODBUS_ADDR_CUP3_CHANNEL1_GAIN_LOW_POINT1 1081
#define MODBUS_ADDR_CUP3_CHANNEL1_GAIN_LOW_POINT2 1082
#define MODBUS_ADDR_CUP3_CHANNEL1_GAIN_LOW_POINT3 1083
#define MODBUS_ADDR_CUP3_CHANNEL1_GAIN_HIGH_POINT2 1084
#define MODBUS_ADDR_CUP3_CHANNEL1_GAIN_HIGH_POINT3 1085
#define MODBUS_ADDR_CUP3_CHANNEL1_GAIN_HIGH_POINT4 1086
#define MODBUS_ADDR_CUP3_CHANNEL2_GAIN_LOW_POINT1 1087
#define MODBUS_ADDR_CUP3_CHANNEL2_GAIN_LOW_POINT2 1088
#define MODBUS_ADDR_CUP3_CHANNEL2_GAIN_LOW_POINT3 1089
#define MODBUS_ADDR_CUP3_CHANNEL2_GAIN_HIGH_POINT2 1090
#define MODBUS_ADDR_CUP3_CHANNEL2_GAIN_HIGH_POINT3 1091
#define MODBUS_ADDR_CUP3_CHANNEL2_GAIN_HIGH_POINT4 1092
#define MODBUS_ADDR_CUP3_CHANNEL3_GAIN_LOW_POINT1 1093
#define MODBUS_ADDR_CUP3_CHANNEL3_GAIN_LOW_POINT2 1094
#define MODBUS_ADDR_CUP3_CHANNEL3_GAIN_LOW_POINT3 1095
#define MODBUS_ADDR_CUP3_CHANNEL3_GAIN_HIGH_POINT2 1096
#define MODBUS_ADDR_CUP3_CHANNEL3_GAIN_HIGH_POINT3 1097
#define MODBUS_ADDR_CUP3_CHANNEL3_GAIN_HIGH_POINT4 1098
#define MODBUS_ADDR_CUP3_CHANNEL4_GAIN_LOW_POINT1 1099
#define MODBUS_ADDR_CUP3_CHANNEL4_GAIN_LOW_POINT2 1100
#define MODBUS_ADDR_CUP3_CHANNEL4_GAIN_LOW_POINT3 1101
#define MODBUS_ADDR_CUP3_CHANNEL4_GAIN_HIGH_POINT2 1102
#define MODBUS_ADDR_CUP3_CHANNEL4_GAIN_HIGH_POINT3 1103
#define MODBUS_ADDR_CUP3_CHANNEL4_GAIN_HIGH_POINT4 1104
#define MODBUS_ADDR_CUP1_CHANNEL1_LOWER_LIMIT 1105
#define MODBUS_ADDR_CUP1_CHANNEL2_LOWER_LIMIT 1106
#define MODBUS_ADDR_CUP1_CHANNEL3_LOWER_LIMIT 1107
#define MODBUS_ADDR_CUP1_CHANNEL4_LOWER_LIMIT 1108
#define MODBUS_ADDR_CUP2_CHANNEL1_LOWER_LIMIT 1109
#define MODBUS_ADDR_CUP2_CHANNEL2_LOWER_LIMIT 1110
#define MODBUS_ADDR_CUP2_CHANNEL3_LOWER_LIMIT 1111
#define MODBUS_ADDR_CUP2_CHANNEL4_LOWER_LIMIT 1112
#define MODBUS_ADDR_CUP3_CHANNEL1_LOWER_LIMIT 1113
#define MODBUS_ADDR_CUP3_CHANNEL2_LOWER_LIMIT 1114
#define MODBUS_ADDR_CUP3_CHANNEL3_LOWER_LIMIT 1115
#define MODBUS_ADDR_CUP3_CHANNEL4_LOWER_LIMIT 1116
#define MODBUS_ADDR_CUP1_CHANNEL1_UPPER_LIMIT 1117
#define MODBUS_ADDR_CUP1_CHANNEL2_UPPER_LIMIT 1118
#define MODBUS_ADDR_CUP1_CHANNEL3_UPPER_LIMIT 1119
#define MODBUS_ADDR_CUP1_CHANNEL4_UPPER_LIMIT 1120
#define MODBUS_ADDR_CUP2_CHANNEL1_UPPER_LIMIT 1121
#define MODBUS_ADDR_CUP2_CHANNEL2_UPPER_LIMIT 1122
#define MODBUS_ADDR_CUP2_CHANNEL3_UPPER_LIMIT 1123
#define MODBUS_ADDR_CUP2_CHANNEL4_UPPER_LIMIT 1124
#define MODBUS_ADDR_CUP3_CHANNEL1_UPPER_LIMIT 1125
#define MODBUS_ADDR_CUP3_CHANNEL2_UPPER_LIMIT 1126
#define MODBUS_ADDR_CUP3_CHANNEL3_UPPER_LIMIT 1127
#define MODBUS_ADDR_CUP3_CHANNEL4_UPPER_LIMIT 1128
#define MODBUS_ADDR_ANALOG_INPUTS_ERROR_STORAGE 1129
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_IN 1130
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_IN_RAND 1131
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_OUT 1132
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION1_OUT_RAND 1133
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_IN 1134
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_IN_RAND 1135
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_OUT 1136
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION2_OUT_RAND 1137
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_IN 1138
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_IN_RAND 1139
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_OUT 1140
#define MODBUS_ADDR_SIM_MECHANISM_PROPAGATION3_OUT_RAND 1141
#define MODBUS_ADDR_SIM_MECHANISM3_INERTIAL_MOTION 1142
#define MODBUS_ADDR_SIM_MECHANISM3_BRAKED_MOTION 1143
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE1 1144
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE2 1145
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE3 1146
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP1_ELECTRODE4 1147
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE1 1148
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE2 1149
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE3 1150
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP2_ELECTRODE4 1151
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE1 1152
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE2 1153
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE3 1154
#define MODBUS_ADDR_SIM_AMPLIFIER_CUP3_ELECTRODE4 1155
#define MODBUS_ADDR_SIM_AMPLIFIER_RANDOM_RATE 1156
#define MODBUS_ADDR_SIM_AMPLIFIER_RANDOM_OFFSET 1157
#define MODBUS_ADDR_SIM_EXTERNAL_LOCK_PERIOD 1158
#define MODBUS_ADDR_SIM_EXTERNAL_LOCK_DURATION 1159
#define MODBUS_ADDR_SIM_EXTERNAL_LOCK_DELAY 1160
#define MODBUS_ADDR_SIM_EVENT_CODE 1161
#define MODBUS_ADDR_SIM_EVENT_PERIOD 1162
#define MODBUS_ADDR_SIM_EVENT_DURATION 1163
#define MODBUS_ADDR_SIM_EVENT_DELAY 1164
#define MODBUS_ADDR_DEBUG_PRINTOUTS 1165
#define MODBUS_ADDR_DEBUG_ARGUMENT1 1166
#define MODBUS_ADDR_DEBUG_ARGUMENT2 1167

#define MODBUS_ADDR_THE_LAST_HOLDING_REGISTER 1167

//..............................................................................
// Modbus Input Register Address Mnemonics (from ModbusRegisters.csv)
//..............................................................................

#define MODBUS_ADDR_CUP1_CHANNEL1_SAMPLE 3001
#define MODBUS_ADDR_CUP1_CHANNEL2_SAMPLE 3002
#define MODBUS_ADDR_CUP1_CHANNEL3_SAMPLE 3003
#define MODBUS_ADDR_CUP1_CHANNEL4_SAMPLE 3004
#define MODBUS_ADDR_CUP1_CHANNEL_ERROR 3005
#define MODBUS_ADDR_CUP2_CHANNEL1_SAMPLE 3006
#define MODBUS_ADDR_CUP2_CHANNEL2_SAMPLE 3007
#define MODBUS_ADDR_CUP2_CHANNEL3_SAMPLE 3008
#define MODBUS_ADDR_CUP2_CHANNEL4_SAMPLE 3009
#define MODBUS_ADDR_CUP2_CHANNEL_ERROR 3010
#define MODBUS_ADDR_CUP3_CHANNEL1_SAMPLE 3011
#define MODBUS_ADDR_CUP3_CHANNEL2_SAMPLE 3012
#define MODBUS_ADDR_CUP3_CHANNEL3_SAMPLE 3013
#define MODBUS_ADDR_CUP3_CHANNEL4_SAMPLE 3014
#define MODBUS_ADDR_CUP3_CHANNEL_ERROR 3015

#define MODBUS_ADDR_THE_LAST_INPUT_REGISTER 3015

//..............................................................................
// Constants related to Modbus registers
//..............................................................................

#define MODBUS_COILS_ADDRESS                MODBUS_ADDR_CUP1_CONTROL

/// This is the number of coils (as defined by Modbus); some of them are read-only, while others are read-write
#define MODBUS_COILS_NUMBER                 (MODBUS_ADDR_THE_LAST_COIL - MODBUS_ADDR_CUP1_CONTROL + 1)


// This directive specifies the starting address of the register area
#define MODBUS_HOLDING_REGISTERS_ADDRESS    MODBUS_ADDR_ERROR_CODE

// The initial registers are of type r/w; this directive specifies number of the r/w registers
#define MODBUS_HOLDING_REGISTERS_NUMBER     (MODBUS_ADDR_THE_LAST_HOLDING_REGISTER - MODBUS_ADDR_ERROR_CODE + 1)

#define MODBUS_CALIBRATION_Y_REGISTERS_ADDRESS    MODBUS_ADDR_CALIBRATION_CURRENT1

#define MODBUS_CALIBRATION_X_REGISTERS_ADDRESS    MODBUS_ADDR_CUP1_CHANNEL1_GAIN_LOW_POINT1


#define MODBUS_INPUT_REGISTERS_ADDRESS      MODBUS_ADDR_CUP1_CHANNEL1_SAMPLE

/// This is the number of read-only input registers
#define MODBUS_INPUT_REGISTERS_NUMBER       (MODBUS_ADDR_THE_LAST_INPUT_REGISTER - MODBUS_ADDR_CUP1_CHANNEL1_SAMPLE + 1)

//..............................................................................
// Definitions of variables concerning Modbus communication
//..............................................................................

extern uint16_t ModbusInputRegisters[MODBUS_INPUT_REGISTERS_NUMBER];
extern bool ModbusCoils[MODBUS_COILS_NUMBER];
extern bool ModbusCoilTrigger[MODBUS_COILS_NUMBER];
extern uint16_t ModbusHoldingRegisters[MODBUS_HOLDING_REGISTERS_NUMBER];


uint16_t holdingIndexFromAddress(uint16_t address);

uint16_t inputIndexFromAddress(uint16_t address);

uint16_t coilIndexFromAddress(uint16_t address);

void initializeModbusRegisters(void);


#endif // SHARED_DATA_H